# Generated by Django 3.2 on 2021-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogapptname', models.CharField(max_length=200, null=True)),
                ('lastnameappt', models.CharField(max_length=200, null=True)),
                ('typeofcut', models.CharField(max_length=200, null=True)),
                ('timetakestocut', models.CharField(max_length=200, null=True)),
                ('costofcut', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('dogname', models.CharField(max_length=200, null=True)),
                ('dogbreed', models.CharField(max_length=200, null=True)),
                ('doggender', models.CharField(max_length=200, null=True)),
                ('doghealth', models.CharField(max_length=200, null=True)),
                ('doghealthphone', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
