# Generated by Django 3.2 on 2021-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogsize',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
