# Generated by Django 3.2 on 2021-05-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogwebsite', '0002_dog_dogsize'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='Dog',
        ),
    ]
