# Generated by Django 3.2 on 2021-05-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogwebsite', '0003_alter_dog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table=None,
        ),
    ]
